TemplateApplication/Models/ViewModels/ListingViewModel.cs
using System.Collections.Generic;
using Models.Models;

namespace TemplateApplication.Models.ViewModels
{
    public class ListingViewModel
    {
        public Listing Listing { get; set; }
        public IEnumerable<State> States { get; set; }
        public IEnumerable<Directory> Directores { get; set; }
        public IEnumerable<Industry> Industries { get; set; }
        public string ListingFormAction { get; set; }
        public string SubmitButtonText { get; set; }
    }
}

TemplateApplication/Models/ViewModels/PricingViewModel.cs
using System.Collections.Generic;
using Models.Models;

namespace TemplateApplication.Models.ViewModels
{
    public class PricingViewModel
    {
        public PricingModel CurrentPricingModel { get; set; }
        public IEnumerable<PricingModel> HistoricalPricingModels { get; set; }
    }
}

TemplateApplication/Models/ViewModels/UserDetailViewModel.cs
using System.Collections.Generic;
using Models.Models;

namespace TemplateApplication.Models.ViewModels
{
    public class UserDetailViewModel
    {
        public UserDetail UserDetail { get; set; }
        public IEnumerable<Listing> UserListings { get; set; }
    }
}

TemplateApplication/Controllers/SiteUtilitiesController.cs
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.Web.Script.Serialization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using Library;
using Library.Exceptions;
// This is the library used to export to CSV.
using Library.Exporter;
using Models;
using Models.Interfaces;
using Models.Models;
using DataTables.Mvc;
using TemplateApplication.Filters;
using TemplateApplication.Models.ViewModels;
using WebMatrix.WebData;

namespace TemplateApplication.Controllers
{
    // To access any of the post methods or controller actions in this controller,
    // the user must be an administrator.
    [Authorize(Roles = "Administrator")]
    [InitializeSimpleMembership]
    public class SiteUtilitiesController : Controller
    {
        private const int StartingPage = 1;
        private const int RecordsPerPage = 10;

        private readonly ITradeLeadRepository _tradeLeadRepository;
        private readonly IListingRepository   _listingRepository;
        private readonly IListingService      _listingService;
        private readonly IValidationService   _validationService;
        private readonly IDatabaseContext     _database;

        private static readonly object Lock = new object();

        public SiteUtilitiesController(ITradeLeadRepository tradeLeadRepository, IListingRepository listingRepository, IDatabaseContext database, IListingService listingService, IValidationService validationService)
        {
            _tradeLeadRepository = tradeLeadRepository;
            _listingRepository   = listingRepository;
            _listingService      = listingService;
            _validationService   = validationService;

            _database = database;
        }

        // This is the Action method for the Listing Conversion utility.
        // This utility is used to convert a "Bulk" listing to a "Manual" listing when a 
        // user returns a form indicating they'd like to pay for a description.
        public ActionResult ListingConversion()
        {
            return View();
        }

        // This procedure converts a "bulk" listing in the database to a "Manual" listing.
        // "Manual" listings have a connected user account so a user can log in and manage them.
        // They also show up in certain utilities, like the billable listings utility.
        // This is the first step of the process when a user signs up for a subscription.
        // We convert their bulk listing to a manual listing so we can create an order for the listing.
        // todo, need to finish up the implementation of this feature.
        [HttpPost]
        public JsonResult ConvertBulkListing(int listingIdentifier, string username, string emailAddress)
        {
            try
            {
                // Make sure a username and email address are provided.
                if(string.IsNullOrEmpty(username) || string.IsNullOrEmpty(emailAddress))
                    return Json(new { errorMessage = "Please provide a username and email address." });
                if(!IsEmailAddressValid(emailAddress))
                    return Json(new { errorMessage = "Please provide valid email address." });

                // Create a linked username and password.
                var newUserID = CreateUserNamePassword(username, emailAddress);
                if (newUserID.HasValue)
                {
                    // Link the newly created user account to the listing.
                    _database.LinkListingToUserID(listingIdentifier, newUserID.Value);
                    // Add a single entry to dbo.Listings_Directories for the default directory.
                    _database.AddDefaultDirectoryToListing(listingIdentifier);
                    // Convert the listing type to "Manual" as it will now be managed by administrators.
                    _listingRepository.UpdateListingType(listingIdentifier, "Manual");
                    // Return a success message.
                    return Json(new { successMessage = "Listing has been converted successfully." });
                }
                return Json(new { errorMessage = "A user could not be created." });
            }
            catch (MembershipCreateUserException exception)
            {
                return Json(new { errorMessage = exception.Message });
            }
            catch (Exception)
            {
                return Json(new { errorMessage = "There was an issue converting this listing." });
            }
        }

        // This helper method creates a new user account and returns the user identifier.
        public int? CreateUserNamePassword(string userName, string email)
        {
            // Check to make sure email addresses are not associated with more than one user account.
            if (!_database.EmailExists(email))
            {
                // Generate a temporary password for the user account.
                var temporaryPassword = Membership.GeneratePassword(8, 1);

                // Create the user account using the temporary password, and associate the email address.
                WebSecurity.CreateUserAndAccount(userName, temporaryPassword);
                var userID = WebSecurity.GetUserId(userName);
                _database.SaveEmailAddress(userID, email);
                return userID;
            }
            // If the email address exists in the system, throw a new exception.
            throw new MembershipCreateUserException("The email address provided exists in the database already.");
        }

        private bool IsEmailAddressValid(string emailAddress)
        {
            return new EmailAddressAttribute().IsValid(emailAddress);
        }

        // Action method for the Trade Lead editor utility.
        public ActionResult TradeLeadEditor()
        {
            TradeLeadParameterSet parameters = new TradeLeadParameterSet
            {
                Page = StartingPage,
                NumberOfRecords = RecordsPerPage
            };
            PagedList<TradeLead> tradeLeads = _tradeLeadRepository.GetTradeLeadsPaged(parameters);
            return View(tradeLeads);
        }

        // Action method for the Billable Listings utility.
        public ActionResult BillableListings()
        {
            BillableListingParameterSet parameters = new BillableListingParameterSet
            {
                Page = StartingPage,
                NumberOfRecords = RecordsPerPage
            };
            PagedList<BillableListingsModel> model = _listingRepository.GetBillableListings(parameters);
            return View(model);
        }

        // Action method for the View Listings utility.
        public ActionResult Listings()
        {
            ManagedListingsReportParameters parameters = new ManagedListingsReportParameters
            {
                Page            = StartingPage,
                NumberOfRecords = RecordsPerPage
            };

            ManagedListingsViewModel model = new ManagedListingsViewModel
            {
                ManagedListings = _listingRepository.GetManagedListings(parameters),
                ListingTypes    = _listingRepository.GetListingTypes().Where(x => x.Type != "Bulk").ToList()
            };

            return View(model);
        }

        // Action method for the Site Users utility.
        public ActionResult Users()
        {
            SiteUsersModel model = new SiteUsersModel
            {
                SiteUsersPaged = _database.GetSiteUsers(StartingPage, RecordsPerPage, null, null, null, null, null)
            };
            return View(model);
        }

        /// <summary>
        /// Returns details about the currently selected user.
        /// </summary>
        /// <param name="id">The user identifier for the selected user.</param>
        /// <returns>View displaying the details for a specified user.</returns>
        public ActionResult UserDetail(int id)
        {
            UserDetailViewModel model = new UserDetailViewModel
            {
                UserDetail   = _database.GetUserDetails(id),
                UserListings = _listingRepository.GetUserListings(id)
            };
            return View(model);
        }

        // Action method fro the Pricing utility.
        public ActionResult Pricing()
        {
            PricingViewModel model = new PricingViewModel
            {
                // Retrieve the current pricing model.
                CurrentPricingModel = _database.GetCurrentListingPricingModel(),
                // Retrieve all the historical changes to the pricing model for display.
                HistoricalPricingModels = _database.GetPricingHistory()
            };
            return View(model);
        }

        // Post method for the Pricing utility form. This POST method saves a new pricing model.
        [HttpPost]
        public ActionResult Pricing(PricingModel currentPricingModel)
        {
            // Validate the pricing model values adhere to required validation.
            if (_validationService.ValidatePricingModel(currentPricingModel))
            {
                try
                {
                    // Save the new pricing model associated to the change user.
                    int currentUserID = WebSecurity.GetUserId(User.Identity.Name);
                    _database.SaveNewPricingModel(currentPricingModel, currentUserID);
                }
                catch (Exception)
                {
                    ModelState.AddModelError("", "There was an error when updating pricing information in the database.");
                }
            }
            else
            {
                // If validation fails, return an explanation as to why, and render the view.
                foreach (KeyValuePair<string, string> entry in _validationService.GetErrorDictionary())
                {

TemplateApplication/Controllers/TradeLeadsController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Library.Exceptions;
using Models.Interfaces;
using Models.Models;
using Services;
using TemplateApplication.Models.ViewModels;
using TemplateApplication.Filters;
using WebMatrix.WebData;

namespace TemplateApplication.Controllers
{
    [InitializeSimpleMembership]
    [ValidateAntiForgeryTokenOnAllPosts]
    public class TradeLeadsController : Controller
    {
        private const int StartingPage         = 1;
        private const int DefaultNumberRecords = 25;

        private readonly ITradeLeadRepository _tradeLeadRepository;
        private readonly IDatabaseContext     _database;

        // Repository and database access classes injected using dependency injection.
        public TradeLeadsController(ITradeLeadRepository tradeLeadRepository, IDatabaseContext database)
        {
            _tradeLeadRepository = tradeLeadRepository;
            _database            = database;
        }

        // View the first page of results for the trade lead listing page.
        public ActionResult Index(string keyword, DateTime? start, DateTime? end, int? industry)
        {
            // If an industry ID has been passed via GET parameter...
            List<int?> industryList = new List<int?>();
            if (industry.HasValue)
            {
                industryList.Add(industry.Value);
            }

            TradeLeadSummaryViewModel model = new TradeLeadSummaryViewModel
            {
                PassedKeyword    = keyword,
                PassedStartDate  = start,
                PassedEndDate    = end,
                PassedIndustryID = industry,
                // Top trade lead records to be displayed in the sidebar.
                TopTradeLeads = _tradeLeadRepository.GetTopTradeLeads(),
                // Return the paged trade leads object. Contains a list of Trade Leads to display and the total number for paging.
                TradeLeads = _tradeLeadRepository.GetTradeLeads(StartingPage, DefaultNumberRecords, keyword, industryList, null, null),
                // Get the list of industries to be displayed in the search control.
                Industries = _database.GetIndustries(),
                IndustryCounts =_database.GetTradeLeadIndustryCount()
            };
            return View(model);
        }

        // View the details for a specific trade lead.
        public ActionResult Details(int id)
        {
            // Increment the view column for this trade lead.
            _tradeLeadRepository.SaveTradeLeadView(id);
            // Get the requested Trade Lead by ID.
            TradeLead tradeLead = _tradeLeadRepository.GetSpecificTradeLead(id);

            TradeLeadDetailsViewModel model = new TradeLeadDetailsViewModel
            {
                TradeLead = tradeLead
            };
            return View(model);
        }

        // Action method for the Create Trade Lead page.
        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            ViewBag.ButtonText = "Create Trade Lead";
            TradeLeadCreateEditViewModel model = new TradeLeadCreateEditViewModel
            {
                TradeLead  = null,
                Industries = _database.GetIndustries()
            };
            return View(model);
        }

        // Action method used to edit a specified Trade Lead.
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id)
        {
            ViewBag.ButtonText = "Save Trade Lead";
            TradeLeadCreateEditViewModel model = new TradeLeadCreateEditViewModel
            {
                TradeLead  = _tradeLeadRepository.GetSpecificTradeLead(id),
                Industries = _database.GetIndustries()
            };
            return View(model);
        }

        #region POST Methods

        // POST Method to return new page of trade lead records without a page refresh.
        [HttpPost]
        public ActionResult GetTradeLeadResults(int pageNumber, int numberPerPage, TradeLeadSearchViewModel search)
        {
            var tradeLeads = _tradeLeadRepository.GetTradeLeads(pageNumber, numberPerPage, search.Keyword, search.IndustryIDs, search.Start, search.End);
            return PartialView("_TradeLeadSummary", tradeLeads);
        }

        // POST method returning the quick view details for a trade lead.
        [HttpPost]
        public ActionResult GetQuickViewDetail(int tradeLeadID)
        {
            // Save a view for the trade lead.
            _tradeLeadRepository.SaveTradeLeadView(tradeLeadID);
            // Retrieve the lead detail and return HTML.
            var tradeLead = _tradeLeadRepository.GetSpecificTradeLead(tradeLeadID);
            return PartialView("_TradeLeadDetail", tradeLead);
        }

        // POST method used to save a new or existing trade lead.
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public JsonResult UpsertTradeLead(TradeLead tradeLead)
        {
            try
            {
                int userID = WebSecurity.GetUserId(User.Identity.Name);
                TradeLeadService service = new TradeLeadService(_tradeLeadRepository);
                service.SaveTradeLead(tradeLead, userID);
            }
            catch (TradeLeadValidationException exception)
            {
                return Json(exception.Message);
            }
            return Json("Trade Lead saved successfully.");
        }

        #endregion
    }
}

TemplateApplication/Views/SiteUtilities/ConfigureDirectories.cshtml
@model TemplateApplication.Models.ViewModels.DirectoryConfigurationViewModel

@{
    ViewBag.Title = "ConfigureDirectories";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@section Styles {
    @Styles.Render("~/Content/assets/global/plugins/datatables/plugins/bootstrap/DataTablesStyling")
}

<div class="portlet light">
    <div class="portlet-title">
        <h2>Configure Site Directories</h2>
        <hr />
    </div>
    <div class="portlet-body">
        <div class="row">
            @if (!Model.DoesDefaultDirectoryExist)
            {
                <div class="col-md-12">
                    <div class="note note-shadow note-info">
                        <strong>
                            No directory has been selected as the default directory. Please choose a directory to be marked as the default.
                        </strong>
                    </div>
                </div>
            }
            <div class="col-md-6">
                <h3>Create New Directory</h3>
                <hr />
                @using (Html.BeginForm("ConfigureDirectories", "SiteUtilities", FormMethod.Post, new { id = "directory-form" }))
                {
                    @Html.ValidationSummary(true, "", new { @class = "note note-danger note-shadow" })
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <label><strong>Directory Name</strong></label>
                                <input id="name-textbox" type="text" class="form-control" name="Directory.Name" />
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="control-label"><strong>Default Directory</strong></label>
                                <div class="checkbox-list">
                                    <label class="checkbox-inline">
                                        <input type="checkbox" name="Directory.IsDefault" value="true" />
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label><strong>Description</strong></label>
                                <textarea id="description-textarea" class="form-control" name="Directory.Description"></textarea>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn blue">Save New Directory</button>
                }
            </div>
            <div class="col-md-6">
                <h3>Site Directories</h3>
                <hr />
                <table id="directory-table" class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Directory ID</th>
                            <th>Directory Name</th>
                            <th>Description</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var directory in Model.Directories)
                        {
                            <tr>
                                <td>@directory.DirectoryID</td>
                                <td>@directory.Name</td>
                                <td>@directory.Description</td>
                                <td><a href="/SiteUtilities/EditDirectory/@directory.DirectoryID" class="btn blue btn-xs edit">Edit</a><button class="btn btn-danger btn-xs delete">Delete</button></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/DatatableScripts")
    @Scripts.Render("~/jQueryValidation")

    <script type="text/javascript">
        $(document).ready(function () {

            var directoryTable = $("#directory-table").DataTable({
                "language":
                {
                    "lengthMenu": "Display _MENU_",
                    "zeroRecords": "No directories found.",
                    "info": "Showing page _PAGE_ of _PAGES_",
                    "infoEmpty": "No records available",
                    "infoFiltered": "(filtered from _MAX_ total records)",
                    "search": "Search "
                },
                "order": [[0, "asc"]],
                "lengthMenu": [
                    [5, 10, 25, 50],
                    [5, 10, 25, 50]
                ],
                "columnDefs": [
                    {
                        "targets": [2],
                        "visible": false,
                        "searchable": false
                    },
                    {
                        "targets": [3],
                        "searchable": false,
                        "orderable": false
                    }
                ]
            });

            $('body').on('click', '.delete', function () {
                var row = $(this).closest("tr")[0];
                // Retrieve the directoryID from the table row.
                var directoryID = directoryTable.row(row).data()[0];

                bootbox.confirm("Are you sure you'd like to delete this directory?", function (result) {
                    if (result === true) {
                        AjaxMethods.DeleteDirectory(directoryID).done(function () {
                            // If the deletion was successful.
                            directoryTable.row(row).remove().draw();
                        }).fail(function () {
                            bootbox.alert("The selected directory could not be deleted.");
                        });
                    }
                });
            });

            // jQuery validation for th pricing model form.
            var validatedForm = $('#directory-form');
            validatedForm.validate({
                // Default input error message container.
                errorElement: 'span',
                // Default input error message class.
                errorClass: 'help-block help-block-error',
                // Do not focus the last invalid input.
                focusInvalid: false,

                rules: {
                    'Directory.Name': {
                        required: true
                    },
                    'Directory.Description': {
                        required: true
                    }
                },
                messages: {
                    'Directory.Name': {
                        required: "Please provide a directory name."
                    },
                    'Directory.Description': {
                        required: "Please provide a directory description."
                    }
                },
                highlight: function (element) {
                    // Hightlight error inputs.
                    // Set error class to the control group.
                    $(element).closest('.form-group').removeClass('has-success').addClass('has-error');
                },
                unhighlight: function (element) {
                    // Revert the change done by hightlight.
                    // Set error class to the control group.
                    $(element).closest('.form-group').removeClass('has-error');
                },
                success: function (label) {
                    // Mark the current input as valid and display OK icons.
                    // Set success class to the control group
                    label.addClass('valid').closest('.form-group').removeClass('has-error').addClass('has-success');
                },
                submitHandler: function (form) {
                    form.submit();
                }
            });
        });
    </script>
}

TemplateApplication/Views/SiteUtilities/EditDirectory.cshtml
@model Models.Models.Directory

@{
    ViewBag.Title = "EditDirectory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="portlet light">
    <div class="portlet-title">
        <h2>Edit Directory</h2>
        <hr />
    </div>
    <div class="portlet-body">
        <div class="row">
            <div class="col-md-6">
                @using (Html.BeginForm("EditDirectory", "SiteUtilities", FormMethod.Post, new { id = "edit-directory-form" }))
                {
                    @Html.ValidationSummary(true, "", new { @class = "note note-danger note-shadow" })
                    @Html.HiddenFor(m => m.DirectoryID)
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <label><strong>Directory Name</strong></label>
                                @Html.TextBoxFor(m => m.Name, new { id = "name-textbox", @class = "form-control" })
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="control-label"><strong>Default Directory</strong></label>
                                <div class="checkbox-list">
                                    <label class="checkbox-inline">
                                        @Html.CheckBoxFor(m => m.IsDefault)
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label><strong>Description</strong></label>
                                @Html.TextAreaFor(m => m.Description, new { id = "description-textarea", @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn blue pull-right">Save Changes</button>
                    <div class="clearfix"></div>
                }
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/jQueryValidation")
    <script type="text/javascript">
        $(document).ready(function () {
            // jQuery validation for the edit directory form.
            var validatedForm = $('#edit-directory-form');
            validatedForm.validate({
                // Default input error message container.
                errorElement: 'span',
                // Default input error message class.
                errorClass: 'help-block help-block-error',
                // Do not focus the last invalid input.
                focusInvalid: false,
                rules: {
                    'Name': {
                        required: true
                    },
                    'Description': {
                        required: true
                    }
                },
                messages: {
                    'Name': {
                        required: "Please provide a directory name."
                    },
                    'Description': {
                        required: "Please provide a directory description."
                    }
                },
                highlight: function (element) {
                    // Hightlight error inputs.
                    // Set error class to the control group.
                    $(element).closest('.form-group').removeClass('has-success').addClass('has-error');
                },
                unhighlight: function (element) {
                    // Revert the change done by hightlight.
                    // Set error class to the control group.
                    $(element).closest('.form-group').removeClass('has-error');
                },
                success: function (label) {
                    // Mark the current input as valid and display OK icons.
                    // Set success class to the control group
                    label.addClass('valid').closest('.form-group').removeClass('has-error').addClass('has-success');
                },
                submitHandler: function (form) {
                    form.submit();
                }
            });
        });
    </script>
}

TemplateApplication/Views/SiteUtilities/UserDetail.cshtml
@model TemplateApplication.Models.ViewModels.UserDetailViewModel

@{
    ViewBag.Title = "UserDetail";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="portlet light">
    <div class="portlet-title">
        <h2>User Details: </h2>
        <div class="row">
            <div col-md-12>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label col-md-4"><strong>UserName:</strong></label>
                        <div class="col-md-8">
                            @Model.UserDetail.UserName
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label col-md-4"><strong>Last Login Date:</strong></label>
                        <div class="col-md-8">
                            @Model.UserDetail.LastLoginDateDisplay
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="portlet-body">
        @if (Model.UserListings != null && Model.UserListings.Any())
        {
            <div class="row">
                <!-- Display the listings that are owned by the user. -->
                @foreach (var listing in Model.UserListings)
                {
                    <div class="col-xs-12 col-sm-6 col-md-4">
                        <div class="portlet light">
                            <div class="portlet-title">
                                <h4><strong>@listing.BusinessName</strong></h4>
                            </div>
                            <div class="portlet-body">
                                <div class="row">
                                    <div class="col-md-12">
                                        <a class="btn btn-block blue" href="/Listings/AdminDetails/@listing.ListingID">View Listing</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        }
        else
        {
            <div class="note note-danger note-shadow">This user does not have any listings connected to their user account.</div>
        }
    </div>
</div>